GRANT REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO slave@'%' IDENTIFIED BY 'eb27acWqa16E1';
GRANT REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO user_py_admin@'%' IDENTIFIED BY 'eb27acWqa16E1';
GRANT REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO user_py_admin_slave@'%' IDENTIFIED BY 'eb27acWqa16E1';
