# f'{ROOT_PATH}/configs/{env}.yaml'
# 注意配置解析出来都是字符串，请不要带单引号或者双引号
# 例如 '0.0.0.0' "0.0.0.0" 都会报错


debug : true
xsrf_cookies : true
xheaders : true

arbitrary_ip : 0.0.0.0
port : 5080
local_ip : 127.0.0.1
translation : true
time_zone : Asia/Shanghai
language_code : zh-hans
cookie_secret : e921bfcd-ace4-4124-8657-69a36e73f58e
login_pwd_rsa_encrypt : True
default_aes_secret : 883d65f06fd447f3a1e69a36e921bfcd
admin_session_key : de0b3fb0c2f44563944a8ce921bfcd5a
front_session_key : 171630947de24c969c28b2d178c4e0fe
valid_code_key : ab1195c6f0084b4f8b007de921bfcd38
token_key : f30a2331813f46d0adc2bcf2e921bfcd

INSTALLED_APPS :
    - admin
    # - huifeng

# 数据库连接字符串，元祖，
# 每组为n个数据库连接，有且只有一个master，可配与不配slave
DATABASE_CONNECTION :
    default :
        connections :
        -
            ROLE: 'master'
            DRIVER : 'mysql+mysqldb'
            UID : user_py_admin
            # 进过AES加密的密码，格式 aes::: + ciphertext
            PASSWD : 'eb27acWqa16E1'
            HOST : 'pya_db_master'
            PORT : 3306
            DATABASE : 'db_py_admin'
            QUERY : {'charset' : 'utf8mb4'}
        -
            ROLE : 'slave'
            DRIVER : 'mysql+mysqldb'
            UID : user_py_admin_slave
            # 进过AES加密的密码，格式 aes::: + ciphertext
            PASSWD : 'eb27acWqa16E1'
            HOST : 'pya_db_slave'
            PORT : 3306
            DATABASE : 'db_py_admin'
            QUERY : {'charset' : 'utf8mb4'}

# default rediscache 其中之一
default_cache: 'default'
